language: java
before_script:
# maven-enforcer-plugin restrictions which work locally are simply ignored (-> great!), but failures occur nevertheless
 - wget http://apache.lauf-forum.at//maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
 - tar xf apache-maven-3.1.1-bin.tar.gz
 - export M2_HOME=./apache-maven-3.1.1
script:
 - apache-maven-3.1.1/bin/mvn verify
