#language: java
before_script:
# maven-enforcer-plugin restrictions which work locally are simply ignored (-> great!), but failures occur nevertheless
 - wget http://apache.lauf-forum.at//maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
 - tar xf apache-maven-3.1.1-bin.tar.gz
 - wget http://dl.google.com/android/android-sdk_r24.3.3-linux.tgz
 - tar xf android-sdk_r24.3.3-linux.tgz
# yes pipe doesn't work and --silent doesn't avoid interaction (licenses need to be confirmed)
 - cd android-sdk-linux && echo y | ./tools/android update sdk --no-ui --obsolete --force && cd ..
script: env M2_HOME=./apache-maven-3.1.1 ANDROID_HOME=./android-sdk-linux ./apache-maven-3.1.1/bin/mvn verify
